-- CreateTable
CREATE TABLE "SiteContentSettings" (
    "id" TEXT NOT NULL,
    "headerLogoText" TEXT NOT NULL DEFAULT 'ORCA TRADERS',
    "headerLogoImageUrl" TEXT,
    "navLinks" JSONB,
    "aiMentorLabel" TEXT NOT NULL DEFAULT 'ORCA AI Mentor',
    "aiMentorHref" TEXT NOT NULL DEFAULT '/mentor',
    "heroBadge" TEXT,
    "heroTitle" TEXT NOT NULL DEFAULT 'Piyasayı Anlamak Artık Daha Akıllı.',
    "heroDescription" TEXT NOT NULL DEFAULT 'Yapay zeka destekli analiz, profesyonel eğitim ve gerçek piyasa simülasyonları ile trading yolculuğunu üst seviyeye taşı.',
    "heroPrimaryCtaLabel" TEXT NOT NULL DEFAULT 'Keşfetmeye Başla',
    "heroPrimaryCtaHref" TEXT NOT NULL DEFAULT '/register',
    "heroSecondaryCtaLabel" TEXT,
    "heroSecondaryCtaHref" TEXT,
    "heroSocialProofCount" TEXT,
    "heroSocialProofLabel" TEXT,
    "heroImageUrl" TEXT,
    "statsItems" JSONB,
    "toolsTitle" TEXT,
    "toolsSubtitle" TEXT,
    "toolsItems" JSONB,
    "featuresTitle" TEXT,
    "featuresSubtitle" TEXT,
    "featureItems" JSONB,
    "communityTitle" TEXT,
    "communityStats" JSONB,
    "communityExtraCount" INTEGER,
    "ctaTitle" TEXT,
    "ctaDescription" TEXT,
    "ctaButtonLabel" TEXT,
    "ctaButtonHref" TEXT,
    "ctaChecklist" JSONB,
    "faviconUrl" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SiteContentSettings_pkey" PRIMARY KEY ("id")
);
